export const coursesData = [
    { title: 'C Programming Mastery', description: 'Master C programming from basics to advanced concepts', category: 'Programming', originalPrice: 5000, discountedPrice: 2500, discount: '50% OFF', image: '/assests/C-programming.png' },
    { title: 'Java Complete Course', description: 'Comprehensive Java development bootcamp', category: 'Programming', originalPrice: 5000, discountedPrice: 2500, discount: '50% OFF', image: '/assests/Java.png' },
    { title: 'Python with AI/ML', description: 'Python programming with AI and Machine Learning', category: 'Programming', originalPrice: 5000, discountedPrice: 2500, discount: '50% OFF', image: '/assests/Python.png' },
    { title: 'Ethical Hacking for Beginners', description: 'Start your journey in cybersecurity concepts', category: 'Cybersecurity', originalPrice: 2000, discountedPrice: 1000, discount: '50% OFF', image: '/assests/Ethical Hacking.png' },
    { title: 'Ethical Hacking VAPT', description: 'Advanced Vulnerability Assessment & Penetration Testing', category: 'Cybersecurity', originalPrice: 6000, discountedPrice: 3000, discount: '50% OFF', image: '/assests/Ethical VAPT.png' },
    { title: 'SOC Analyst Professional', description: 'Become a Security Operations Center expert', category: 'Cybersecurity', originalPrice: 6000, discountedPrice: 3000, discount: '50% OFF', image: '/assests/Soc Analyst.png' },
    { title: 'Web Development Bootcamp', description: 'Full-stack web development from scratch', category: 'Web Development', originalPrice: 5000, discountedPrice: 2500, discount: '50% OFF', image: '/assests/Web Developement.png' },
    { title: 'API Testing Masterclass', description: 'Complete API testing and automation course', category: 'Web Development', originalPrice: 10000, discountedPrice: 5000, discount: '50% OFF', image: '/assests/API Testing.png' }
];

export const gadgetsData = [
    { name: 'USB Rubber Ducky', description: 'Keystroke injection tool for penetration testing', category: 'USB Devices', originalPrice: 8000, discountedPrice: 4000, discount: '50% OFF', image: '/assests/Ducky.png' },
    { name: 'Bash Bunny', description: 'Multi-function USB attack and automation platform', category: 'USB Devices', originalPrice: 20000, discountedPrice: 10000, discount: '50% OFF', image: '/assests/Bluetooth.png' },
    { name: 'KeyGrabber USB Keylogger', description: 'Hardware keylogger for security assessments', category: 'USB Devices', originalPrice: 12000, discountedPrice: 6000, discount: '50% OFF', image: '/assests/Bunny.png' },
    { name: 'Wi-Fi Pineapple', description: 'Wireless auditing and penetration testing platform', category: 'Network Tools', originalPrice: 20000, discountedPrice: 10000, discount: '50% OFF', image: '/assests/Flipper.png' },
    { name: 'LAN Turtle', description: 'Covert network implant for remote access', category: 'Network Tools', originalPrice: 15000, discountedPrice: 7500, discount: '50% OFF', image: '/assests/Lan.png' },
    { name: 'ESP8266/ESP32', description: 'Wi-Fi and Bluetooth microcontroller modules', category: 'Network Tools', originalPrice: 2000, discountedPrice: 1000, discount: '50% OFF', image: '/assests/Usb.png' },
    { name: 'Flipper Zero', description: 'Multi-tool device for hackers and geeks', category: 'Multi-Tools', originalPrice: 30000, discountedPrice: 15000, discount: '50% OFF', image: '/assests/Flipper.png' },
    { name: 'Proxmark3', description: 'RFID research and penetration testing tool', category: 'Multi-Tools', originalPrice: 35000, discountedPrice: 17500, discount: '50% OFF', image: '/assests/promarks.png' },
    { name: 'HackRF One', description: 'Software-defined radio platform for RF analysis', category: 'SDR Tools', originalPrice: 50000, discountedPrice: 25000, discount: '50% OFF', image: '/assests/Flipper.png' },
    { name: 'Bluetooth Jammer', description: 'Signal disruption device for security testing', category: 'SDR Tools', originalPrice: 25000, discountedPrice: 12500, discount: '50% OFF', image: '/assests/Bluetooth.png' },
    { name: 'Raspberry Pi Zero W', description: 'Compact wireless-enabled single-board computer', category: 'IoT Devices', originalPrice: 3000, discountedPrice: 1500, discount: '50% OFF', image: '/assests/Promark.png' }
];

export const careersData = [
    { title: 'Frontend Development Instructor', category: 'Frontend', location: 'Remote', type: 'Full-time', salary: '₹10,000 - ₹30,000', experience: '3-5 years', description: 'Lead and inspire students in mastering modern frontend technologies including React, TypeScript, and modern CSS frameworks.', responsibilities: ['Develop comprehensive curriculum for frontend development courses', 'Conduct live coding sessions and workshops', 'Mentor students and provide code reviews'], requirements: ['Expert knowledge in React, TypeScript, HTML5, CSS3', '3+ years of professional frontend development experience', 'Previous teaching or mentoring experience preferred'], icon: '🎨' },
    { title: 'Backend Development Teacher', category: 'Backend', location: 'Hybrid', type: 'Full-time', salary: '₹10,000 - ₹30,000', experience: '5-7 years', description: 'Educate and guide students through server-side development, databases, APIs, and cloud infrastructure.', responsibilities: ['Design and deliver backend development curriculum', 'Teach Node.js, Python, databases, and API design', 'Guide students through real-world backend projects'], requirements: ['Strong experience with Node.js, Python, or similar', 'Deep understanding of databases (SQL and NoSQL)', 'Experience with RESTful APIs and GraphQL'], icon: '⚙️' },
    { title: 'Cybersecurity Instructor', category: 'Cybersecurity', location: 'On-site', type: 'Full-time', salary: '₹10,000 - ₹30,000', experience: '5-7 years', description: 'Train the next generation of cybersecurity professionals in ethical hacking, network security, and threat analysis.', responsibilities: ['Develop cybersecurity training programs and labs', 'Teach ethical hacking, penetration testing, and security auditing', 'Create hands-on security exercises and CTF challenges'], requirements: ['Professional certifications (CEH, OSCP, CISSP, etc.)', '5+ years in cybersecurity or related field', 'Experience with security tools and frameworks'], icon: '🔒' },
    { title: 'Full Stack Development Mentor', category: 'Frontend/Backend', location: 'Remote', type: 'Part-time', salary: '₹10,000 - ₹30,000', experience: '3-5 years', description: 'Support students learning full-stack development through one-on-one mentoring and project guidance.', responsibilities: ['Provide personalized mentoring sessions', 'Review student projects and provide feedback', 'Help debug and troubleshoot code issues'], requirements: ['Full-stack development experience', 'Strong problem-solving skills', 'Patience and excellent communication'], icon: '🧑‍🏫' },
    { title: 'Cloud & DevOps Instructor', category: 'Backend/DevOps', location: 'Remote', type: 'Full-time', salary: '₹10,000 - ₹30,000', experience: '5-7 years', description: 'Teach cloud architecture, containerization, CI/CD pipelines, and infrastructure as code to aspiring DevOps engineers.', responsibilities: ['Create comprehensive DevOps curriculum', 'Teach Docker, Kubernetes, and cloud services', 'Guide students through CI/CD implementation'], requirements: ['Experience with AWS/Azure/GCP', 'Strong knowledge of Docker and Kubernetes', 'CI/CD pipeline expertise'], icon: '☁️' },
    { title: 'Network Security Teacher', category: 'Cybersecurity', location: 'Hybrid', type: 'Full-time', salary: '₹10,000 - ₹30,000', experience: '5-7 years', description: 'Educate students on network security fundamentals, firewalls, VPNs, and advanced threat detection.', responsibilities: ['Develop network security curriculum', 'Teach network protocols and security measures', 'Conduct lab exercises on firewalls and IDS/IPS'], requirements: ['Network security certifications (CCNP Security, etc.)', 'Deep understanding of TCP/IP, routing, and switching', 'Experience with security appliances and SIEM tools'], icon: '🌐' }
];
